apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Keycloak
  namespace: my-argocd
spec:
  destination:
    name: ''
    namespace: rhbk3
    server: 'https://kubernetes.default.svc'
  source:
    path: kc
    repoURL: 'https://github.com/viniciusfcf/rhbk-101'
    targetRevision: main
  sources: []
  project: Keycloak
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
