apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  destination:
    name: ''
    namespace: rhbk5
    server: 'https://kubernetes.default.svc'
  source:
    path: kc
    repoURL: 'https://github.com/viniciusfcf/rhbk-101'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
